#!/bin/bash

# DNS server details
dns_server="0"
dns_port=53

# Domain to query
domain="google.com"

# Construct the DNS request packet
dns_request=$(printf "\x00\x01\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x06google\x03com\x00\x00\x01\x00\x01")

# Send the DNS request using socat with TCP
echo -ne $dns_request | socat - TCP:$dns_server:$dns_port
